### PR TITLE
Add navigation bar

### LINKED ISSUE #18: Add navigation menu

### PR DESCRIPTION
**Pull request by alecrem**
Close #18

### CODE REVIEW

**Comment by alecrem** [comment]
@shokaji Please review and approve (if you think it's OK) but don't merge yet. I need to check if the card is assigned to me on Dework.

**Comment by alecrem** [comment]
https://asobiya-website-git-feature-issue-18add-navigation-bar-asobiya.vercel.app/members

**Review by shokaji — COMMENTED** [review]
LGTM！

**Review by shokaji — APPROVED** [review]
Good!

**Pull request merged**
